### ISSUE TITLE
[Feature Request] Allow fullscreen for other view

### ISSUE THREAD

**Issue by Quorafind** [cmoskvitin/obsidian-prozen#1]
It will be nice to make other view works like markdownview.

**Comment by Quorafind** [comment]
If you allow me to work on this, I can make a pr for this.

**Comment by cmoskvitin** [comment]
> If you allow me to work on this, I can make a pr for this.

Hi! Sure go ahead :)

**Comment by cmoskvitin** [comment]
@Quorafind I've just checked on my local instance what your change getActiveViewOfType(MarkdownView) -> getActiveViewOfType(ItemView) does. So it allows for graph view to go fullscreen as well. Nice find, thank you! What other views are out there in Obsidian?

**Comment by Quorafind** [comment]
It works with all plugin's itemview like `Graph`, `Memos`, `Daily Notes Editor` and also fileview (which extends from itemview) like `Kanban`, `Excalidraw` and so on.

**Comment by Quorafind** [comment]
If you want it robuster, you can filter out some view like `file-explorer` `search` `backlink` `outline` or some special view from Obsidian. But I tried to call it when I searched, nothing happened, I guessed Obsidian did something for filtering them out.

**Comment by cmoskvitin** [comment]
@Quorafind all right, merged it! Thank you very much for your help!
