### ISSUE TITLE
missing main.js file

### ISSUE THREAD

**Issue by chad-bennett** [cmoskvitin/obsidian-prozen#4]
windows 11, most current version of obsidian. 

there is no main.js file for download. tried renaming main.ts to main.js but still won't work. can see it in the plugin list but get the error that "failed to load obsidian-prozen".

**Comment by cmoskvitin** [comment]
Hi, @chad-bennett! Please grab the files from the [Releases page](https://github.com/cmoskvitin/obsidian-prozen/releases/tag/0.2).

**Comment by cmoskvitin** [comment]
I've added the link to Releases page to the README.md

**Comment by chad-bennett** [comment]
Thank you. I like the simplicity of the plugin.

chad
___________________________
chad bennett
teacher.artist.student

my homepage<https://publish.obsidian.md/mister-chad/website/welcome>
________________________________
